'use client';

/* The admin editor previews user-selected media from local or uploaded URLs. */
/* eslint-disable @next/next/no-img-element */

import Link from 'next/link';
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowUpRight, BarChart3, BookOpen, Check, ChevronRight, CircleHelp, FileText, HeartHandshake, Image as ImageIcon, LayoutDashboard, LogOut, Mail, Menu, Newspaper, Plus, RefreshCw, Search, Settings2, ShieldCheck, Trash2, Upload, UsersRound, X } from 'lucide-react';
import { BrandLockup } from '@/components/logo';
import { useLanguage } from '@/components/language';
import type { AdminData, ContentCollection } from '@/lib/content-types';

type Collection = keyof AdminData;
type Section = Collection | 'overview' | 'account';
type Entry = { id: string; submittedAt?: string; status?: string; source?: Section; [key: string]: unknown };
type Translate = (en: string, ne: string) => string;
type Field = { key: string; en: string; ne: string; kind?: 'localized' | 'body' | 'asset' | 'select' | 'number' | 'checkbox' | 'email' | 'url'; options?: string[]; optional?: boolean; help?: [string, string] };

const sections: { id: Section; en: string; ne: string; group: 'workspace' | 'inbox' | 'system'; icon: typeof LayoutDashboard }[] = [
  { id: 'overview', en: 'Overview', ne: 'अवलोकन', group: 'workspace', icon: LayoutDashboard },
  { id: 'committeeMembers', en: 'Leadership & committees', ne: 'नेतृत्व तथा समितिहरू', group: 'workspace', icon: UsersRound },
  { id: 'notices', en: 'News & notices', ne: 'समाचार तथा सूचना', group: 'workspace', icon: Newspaper },
  { id: 'activities', en: 'Events & activities', ne: 'कार्यक्रम तथा गतिविधि', group: 'workspace', icon: HeartHandshake },
  { id: 'blogPosts', en: 'Blog', ne: 'ब्लग', group: 'workspace', icon: BookOpen },
  { id: 'galleryItems', en: 'Gallery', ne: 'फोटो तथा भिडियो', group: 'workspace', icon: ImageIcon },
  { id: 'documents', en: 'Publications & downloads', ne: 'प्रकाशन तथा डाउनलोड', group: 'workspace', icon: FileText },
  { id: 'heroSlides', en: 'Homepage', ne: 'गृहपृष्ठ', group: 'workspace', icon: LayoutDashboard },
  { id: 'pages', en: 'About & chairperson', ne: 'हाम्रो बारेमा तथा अध्यक्ष', group: 'workspace', icon: BookOpen },
  { id: 'stats', en: 'Statistics', ne: 'तथ्याङ्क', group: 'workspace', icon: BarChart3 },
  { id: 'values', en: 'Values', ne: 'मूल्य मान्यता', group: 'workspace', icon: HeartHandshake },
  { id: 'messages', en: 'Contact messages', ne: 'सम्पर्क सन्देश', group: 'inbox', icon: Mail },
  { id: 'applications', en: 'Membership applications', ne: 'सदस्यता आवेदन', group: 'inbox', icon: UsersRound },
  { id: 'settings', en: 'Site settings', ne: 'साइट सेटिङ', group: 'system', icon: Settings2 },
  { id: 'account', en: 'My account', ne: 'मेरो खाता', group: 'system', icon: ShieldCheck },
];
const localized = (key: string, en: string, ne: string, body = false): Field => ({ key, en, ne, kind: body ? 'body' : 'localized' });
const imageField: Field = { key: 'image', en: 'Image', ne: 'तस्बिर', kind: 'asset', optional: true };
const dateField: Field = { key: 'date', en: 'Date', ne: 'मिति', help: ['Use a clear date, for example 2026-09-07.', 'स्पष्ट मिति लेख्नुहोस्, जस्तै 2026-09-07।'] };
const titleField = localized('title', 'Title', 'शीर्षक');
const bodyField = localized('body', 'Content', 'विवरण', true);
const schemas: Record<ContentCollection, Field[]> = {
  committeeMembers: [localized('name', 'Full name', 'पूरा नाम'), localized('role', 'Position / role', 'पद / भूमिका'), { key: 'category', en: 'Committee level', ne: 'समितिको तह', kind: 'select', options: ['Central', 'Province', 'District', 'Unit', 'International'] }, localized('location', 'Location', 'स्थान'), imageField, { key: 'phone', en: 'Phone number', ne: 'फोन नम्बर', optional: true }, { key: 'accent', en: 'Accent', ne: 'रङ संकेत', help: ['A display accent, such as red.', 'प्रदर्शन रङको संकेत, जस्तै red।'] }],
  notices: [titleField, { key: 'category', en: 'Category', ne: 'वर्ग', kind: 'select', options: ['Notice', 'Press release', 'Tender', 'News'] }, dateField, localized('excerpt', 'Summary', 'सारांश', true), bodyField, { key: 'file', en: 'Attachment', ne: 'संलग्न फाइल', kind: 'asset', optional: true }, { ...imageField, en: 'Preview image', ne: 'पूर्वावलोकन तस्बिर' }, { key: 'urgent', en: 'Mark as urgent', ne: 'जरुरीको रूपमा राख्नुहोस्', kind: 'checkbox', optional: true }],
  blogPosts: [titleField, { key: 'slug', en: 'URL slug', ne: 'यूआरएल स्लग', help: ['Lowercase letters, numbers and hyphens only, e.g. workers-on-the-road.', 'साना अङ्ग्रेजी अक्षर, अङ्क र हाइफन मात्र प्रयोग गर्नुहोस्।'] }, localized('category', 'Category', 'वर्ग'), dateField, { key: 'readTime', en: 'Reading time', ne: 'पढ्न लाग्ने समय' }, { ...imageField, optional: false }, localized('excerpt', 'Summary', 'सारांश', true), bodyField],
  galleryItems: [titleField, { key: 'type', en: 'Media type', ne: 'माध्यमको प्रकार', kind: 'select', options: ['photo', 'video'] }, imageField, { key: 'video', en: 'Video URL or file', ne: 'भिडियो यूआरएल वा फाइल', kind: 'asset', optional: true }, { key: 'size', en: 'Display shape', ne: 'प्रदर्शन आकार', kind: 'select', options: ['wide', 'tall', 'square'] }],
  documents: [titleField, localized('description', 'Description', 'विवरण', true), { key: 'category', en: 'Category', ne: 'वर्ग', kind: 'select', options: ['Acts & regulations', 'Directives', 'Publications'] }, dateField, { key: 'file', en: 'Document file', ne: 'कागजात फाइल', kind: 'asset' }, { ...imageField, en: 'Preview image', ne: 'पूर्वावलोकन तस्बिर' }, { key: 'type', en: 'File type', ne: 'फाइल प्रकार' }, { key: 'size', en: 'File size label', ne: 'फाइलको आकार' }],
  heroSlides: [localized('kicker', 'Eyebrow / short label', 'छोटो परिचय'), titleField, localized('sub', 'Supporting text', 'सहायक पाठ', true), { ...imageField, optional: false }],
  activities: [titleField, dateField, bodyField, imageField],
  pages: [titleField, bodyField, imageField],
  stats: [localized('label', 'Label', 'शीर्षक'), { key: 'value', en: 'Value', ne: 'सङ्ख्या', kind: 'number' }, { key: 'suffix', en: 'Suffix', ne: 'प्रत्यय', optional: true, help: ['For example + or %. Leave empty when not needed.', 'जस्तै + वा %। आवश्यक नभए खाली राख्नुहोस्।'] }],
  values: [titleField, bodyField, { key: 'icon', en: 'Icon', ne: 'चिह्न', kind: 'select', options: ['shield', 'eye', 'flag', 'users', 'heart', 'book', 'megaphone', 'bus', 'map', 'handshake'] }, { key: 'number', en: 'Display number', ne: 'प्रदर्शन नम्बर' }],
  settings: [localized('siteTitle', 'Site title', 'साइटको शीर्षक'), localized('description', 'Search description', 'खोज विवरण', true), localized('mission', 'Mission', 'उद्देश्य', true), localized('address', 'Office address', 'कार्यालयको ठेगाना'), { key: 'phone', en: 'Phone number', ne: 'फोन नम्बर' }, { key: 'email', en: 'Email address', ne: 'इमेल ठेगाना', kind: 'email' }, { key: 'facebook', en: 'Facebook URL', ne: 'फेसबुक यूआरएल', kind: 'url', optional: true }, { key: 'instagram', en: 'Instagram URL', ne: 'इन्स्टाग्राम यूआरएल', kind: 'url', optional: true }],
};
const isInbox = (collection: Section) => collection === 'messages' || collection === 'applications';
function localValue(value: unknown, lang: 'en' | 'ne'): string {
  if (value && typeof value === 'object' && !Array.isArray(value)) { const text = value as Record<string, unknown>; return String(text[lang] || text.en || ''); }
  return value == null ? '' : String(value);
}
function entryTitle(entry: Entry, lang: 'en' | 'ne') { return localValue(entry.name || entry.title || entry.label || entry.siteTitle || entry.email || entry.id, lang); }
function entries(data: AdminData | null, collection: Collection): Entry[] { return (data?.[collection] ?? []) as unknown as Entry[]; }
function statusName(value: unknown, t: Translate) {
  const names: Record<string, [string, string]> = { Published: ['Published', 'प्रकाशित'], Draft: ['Draft', 'मस्यौदा'], New: ['New', 'नयाँ'], Reviewed: ['Reviewed', 'समीक्षा गरिएको'], Resolved: ['Resolved', 'समाधान भएको'], Approved: ['Approved', 'स्वीकृत'], Rejected: ['Rejected', 'अस्वीकृत'] };
  const raw = String(value || 'Published'); return names[raw] ? t(...names[raw]) : raw;
}
function Status({ value, t }: { value: unknown; t: Translate }) { const status = String(value || 'Published'); return <span className={`ant-status ${status === 'Draft' || status === 'New' ? 'ant-status-pending' : status === 'Rejected' ? 'ant-status-rejected' : ''}`}><i />{statusName(status, t)}</span>; }
async function request<T>(url: string, options?: RequestInit): Promise<T> {
  const response = await fetch(url, { credentials: 'same-origin', ...options });
  if (response.status === 401) { window.location.assign('/admin/login'); throw new Error('Your session has expired. Please sign in again.'); }
  const json = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(json.error || `Request failed (${response.status}). Please try again.`);
  return json as T;
}

export function AdminConsole({ email }: { email: string }) {
  const { lang, setLang } = useLanguage();
  const t: Translate = (en, ne) => lang === 'ne' ? ne : en;
  const [active, setActive] = useState<Section>('overview');
  const [data, setData] = useState<AdminData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [mobileOpen, setMobileOpen] = useState(false);
  const [editing, setEditing] = useState<{ collection: ContentCollection; entry: Entry | null } | null>(null);
  const [viewing, setViewing] = useState<{ collection: 'messages' | 'applications'; entry: Entry } | null>(null);
  const [deleting, setDeleting] = useState<{ collection: Collection; entry: Entry } | null>(null);
  const [busy, setBusy] = useState(false);
  const [deleteError, setDeleteError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await request<AdminData>('/api/admin/content')); } catch (err) { setError(err instanceof Error ? err.message : 'Could not load content.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 5000); return () => window.clearTimeout(timer); }, [toast]);
  const navigate = (section: Section) => { setActive(section); setSearch(''); setStatusFilter('all'); setMobileOpen(false); };
  const section = sections.find((item) => item.id === active)!;
  const allRows = active === 'overview' || active === 'account' ? [] : entries(data, active);
  const rows = allRows.filter((entry) => (statusFilter === 'all' || String(entry.status || 'Published') === statusFilter) && JSON.stringify(entry).toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  const notifySaved = async () => { setEditing(null); setViewing(null); setToast(t('Changes saved successfully.', 'परिवर्तन सुरक्षित गरियो।')); await load(); };
  const remove = async () => {
    if (!deleting) return; setBusy(true); setDeleteError('');
    try { await request('/api/admin/content', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ collection: deleting.collection, id: deleting.entry.id }) }); setDeleting(null); setViewing(null); setToast(t('Record deleted.', 'अभिलेख हटाइयो।')); await load(); } catch (err) { setDeleteError(err instanceof Error ? err.message : t('Delete failed.', 'हटाउन सकिएन।')); } finally { setBusy(false); }
  };
  const logout = async () => { setBusy(true); try { await request('/api/auth/logout', { method: 'POST' }); window.location.assign('/admin/login'); } catch (err) { setError(err instanceof Error ? err.message : 'Sign out failed.'); setBusy(false); } };
  const addAllowed = active !== 'overview' && active !== 'account' && !isInbox(active) && (active !== 'settings' || allRows.length === 0) && (active !== 'pages' || !['about', 'chairperson'].every((id) => allRows.some((entry) => entry.id === id)));
  return <main className={`ant-admin ${lang === 'ne' ? 'ant-nepali' : ''}`}>
    {mobileOpen && <button className="ant-sidebar-scrim" onClick={() => setMobileOpen(false)} aria-label={t('Close navigation', 'नेभिगेसन बन्द गर्नुहोस्')} />}
    <aside className={`ant-sidebar ${mobileOpen ? 'ant-sidebar-open' : ''}`} aria-label={t('Administration navigation', 'प्रशासन नेभिगेसन')}>
      <Link href="/" className="ant-sidebar-brand" aria-label="ANTWU"><BrandLockup inverse /></Link>
      <div className="ant-workspace-label"><span />{t('CONTENT WORKSPACE', 'सामग्री कार्यक्षेत्र')}</div>
      <nav className="ant-navigation">{(['workspace', 'inbox', 'system'] as const).map((group) => <div className="ant-nav-group" key={group}><p>{group === 'workspace' ? t('MANAGE CONTENT', 'सामग्री व्यवस्थापन') : group === 'inbox' ? t('YOUR INBOX', 'प्राप्त सन्देश') : t('ADMINISTRATION', 'प्रशासन')}</p>{sections.filter((item) => item.group === group).map(({ id, en, ne, icon: Icon }) => <button key={id} type="button" className={active === id ? 'ant-nav-active' : ''} aria-current={active === id ? 'page' : undefined} onClick={() => navigate(id)}><Icon size={17} strokeWidth={1.65} /><span>{t(en, ne)}</span>{isInbox(id) && data && entries(data, id as Collection).filter((item) => item.status === 'New').length > 0 && <b>{entries(data, id as Collection).filter((item) => item.status === 'New').length}</b>}</button>)}</div>)}</nav>
      <div className="ant-sidebar-foot"><ShieldCheck size={17} /><span>{t('Secure admin workspace', 'सुरक्षित प्रशासन कार्यक्षेत्र')}<small>ANTWU · {new Date().getFullYear()}</small></span></div>
    </aside>
    <div className="ant-main">
      <header className="ant-topbar"><div className="ant-breadcrumb"><button className="ant-icon-button ant-mobile-menu" type="button" onClick={() => setMobileOpen(true)} aria-label={t('Open navigation', 'नेभिगेसन खोल्नुहोस्')}><Menu size={22} /></button><span>ANTWU</span><ChevronRight size={14} /><strong>{t(section.en, section.ne)}</strong></div><div className="ant-topbar-actions"><div className="ant-language" role="group" aria-label={t('Interface language', 'इन्टरफेस भाषा')}><button type="button" onClick={() => setLang('en')} aria-pressed={lang === 'en'}>EN</button><button type="button" onClick={() => setLang('ne')} aria-pressed={lang === 'ne'}>ने</button></div><Link href="/" className="ant-public-link" target="_blank" rel="noreferrer">{t('View website', 'वेबसाइट हेर्नुहोस्')}<ArrowUpRight size={15} /></Link><button type="button" className="ant-account-avatar" onClick={() => navigate('account')} title={email} aria-label={t('My account', 'मेरो खाता')}>{email.slice(0, 2).toUpperCase()}</button></div></header>
      <div className="ant-content">
        {error && <div className="ant-alert ant-alert-error" role="alert"><span>{error}</span><button type="button" onClick={() => void load()}>{t('Retry', 'पुनः प्रयास')}</button></div>}
        {loading && !data ? <div className="ant-loading" role="status"><span className="ant-spinner" /><h2>{t('Opening your workspace…', 'कार्य क्षेत्र खुल्दैछ…')}</h2><p>{t('Loading content and submissions.', 'सामग्री तथा आवेदन लोड हुँदैछ।')}</p></div> : data && active === 'overview' ? <Overview data={data} t={t} lang={lang} navigate={navigate} /> : active === 'account' ? <Account email={email} t={t} onLogout={logout} logoutBusy={busy} /> : data && <>
          <div className="ant-page-heading"><div><span className="ant-eyebrow">{isInbox(active) ? t('COMMUNITY INBOX', 'समुदायका सन्देश') : t('CONTENT MANAGEMENT', 'सामग्री व्यवस्थापन')}</span><h1>{t(section.en, section.ne)}</h1><p>{isInbox(active) ? t('Review submissions, open attachments and keep track of follow-ups.', 'प्राप्त विवरण, संलग्न फाइल र पछिल्लो अवस्थाको समीक्षा गर्नुहोस्।') : active === 'settings' ? t('Keep the union’s contact details and website information up to date.', 'संघको सम्पर्क र वेबसाइटको जानकारी अद्यावधिक राख्नुहोस्।') : t('Create and manage the content your community sees.', 'समुदायले हेर्ने सामग्री सिर्जना र व्यवस्थापन गर्नुहोस्।')}</p></div>{addAllowed && <button type="button" className="ant-button ant-button-primary" onClick={() => setEditing({ collection: active as ContentCollection, entry: null })}><Plus size={17} />{t('Add record', 'अभिलेख थप्नुहोस्')}</button>}</div>
          <section className="ant-panel"><div className="ant-table-toolbar"><label className="ant-search"><Search size={17} /><span className="ant-sr-only">{t('Search records', 'अभिलेख खोज्नुहोस्')}</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('Search names, titles or details…', 'नाम, शीर्षक वा विवरण खोज्नुहोस्…')} /></label><div className="ant-toolbar-right">{active !== 'settings' && <label><span className="ant-sr-only">{t('Filter by status', 'अवस्थाअनुसार छान्नुहोस्')}</span><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">{t('All statuses', 'सबै अवस्था')}</option>{(isInbox(active) ? [...new Set(['New', 'Reviewed', ...allRows.map((entry) => String(entry.status || 'New'))])] : ['Published', 'Draft']).map((status) => <option key={status} value={status}>{statusName(status, t)}</option>)}</select></label>}<button type="button" className="ant-icon-button" disabled={loading} onClick={() => void load()} aria-label={t('Refresh records', 'अभिलेख पुनः लोड गर्नुहोस्')}><RefreshCw size={17} className={loading ? 'ant-spinning' : ''} /></button></div></div>
            {rows.length > 0 && (<div className="ant-table-wrap"><table className="ant-table"><thead><tr><th>{isInbox(active) ? t('Sender / applicant', 'पठाउने / आवेदक') : t('Record', 'अभिलेख')}</th><th>{t('Details', 'विवरण')}</th>{active !== 'settings' && <th>{t('Status', 'अवस्था')}</th>}<th className="ant-actions-cell">{t('Actions', 'कार्य')}</th></tr></thead><tbody>{rows.map((entry) => <tr key={entry.id}><td><div className="ant-record-cell">{typeof entry.image === 'string' && entry.image && <img className="ant-record-image" src={entry.image} alt="" />}{active === 'committeeMembers' && !entry.image && <span className="ant-record-initials">{entryTitle(entry, lang).split(' ').map((part) => part[0]).slice(0, 2).join('')}</span>}<div><strong>{entryTitle(entry, lang)}</strong><small>{isInbox(active) ? localValue(entry.email || entry.phone, lang) : active === 'settings' ? localValue(entry.email, lang) : entry.slug ? `/${String(entry.slug)}` : typeof entry.name === 'object' || typeof entry.title === 'object' || typeof entry.label === 'object' ? t('English + नेपाली', 'नेपाली + English') : entry.id}</small></div></div></td><td><span>{localValue(entry.category || entry.role || entry.type || (active === 'stats' ? `${entry.value}${entry.suffix || ''}` : entry.id === 'chairperson' ? t('Chairperson message', 'अध्यक्षको सन्देश') : entry.id === 'about' ? t('About page', 'हाम्रो बारेमा पृष्ठ') : entry.phone || ''), lang)}</span><small>{entry.submittedAt ? new Date(String(entry.submittedAt)).toLocaleString(lang === 'ne' ? 'ne-NP' : 'en-GB', { dateStyle: 'medium', timeStyle: 'short' }) : localValue(entry.date, lang)}</small></td>{active !== 'settings' && <td><Status value={entry.status} t={t} /></td>}<td className="ant-actions-cell"><div className="ant-row-actions"><button type="button" className="ant-text-button" onClick={() => isInbox(active) ? setViewing({ collection: active as 'messages' | 'applications', entry }) : setEditing({ collection: active as ContentCollection, entry })}>{isInbox(active) ? t('Review', 'समीक्षा') : t('Edit', 'सम्पादन')}</button>{active !== 'settings' && <button type="button" className="ant-icon-button ant-delete-button" onClick={() => { setDeleteError(''); setDeleting({ collection: active as Collection, entry }); }} aria-label={`${t('Delete', 'हटाउनुहोस्')} ${entryTitle(entry, lang)}`}><Trash2 size={16} /></button>}</div></td></tr>)}</tbody></table></div>)}
            {!rows.length && <div className="ant-empty"><Search size={27} /><h2>{search || statusFilter !== 'all' ? t('No matching records', 'मिल्ने अभिलेख छैन') : t('Nothing here yet', 'अहिले कुनै अभिलेख छैन')}</h2><p>{search || statusFilter !== 'all' ? t('Try another search or clear the filters.', 'अर्को शब्द खोज्नुहोस् वा फिल्टर हटाउनुहोस्।') : isInbox(active) ? t('New website submissions will appear here.', 'वेबसाइटबाट आएका नयाँ विवरण यहाँ देखिनेछन्।') : t('Add the first record to this collection.', 'यस खण्डमा पहिलो अभिलेख थप्नुहोस्।')}</p>{(search || statusFilter !== 'all') && <button type="button" className="ant-button" onClick={() => { setSearch(''); setStatusFilter('all'); }}>{t('Clear filters', 'फिल्टर हटाउनुहोस्')}</button>}</div>}
            <footer className="ant-table-footer"><span>{t(`Showing ${rows.length} of ${allRows.length} records`, `${allRows.length} मध्ये ${rows.length} अभिलेख`)}</span><span>{t('Changes appear after you save.', 'सुरक्षित गरेपछि परिवर्तन देखिन्छ।')}</span></footer>
          </section>
        </>}
      </div>
      <footer className="ant-main-footer"><span>{t('ANTWU administration', 'अन्तु प्रशासन')}</span><span>{t('A stronger union, together.', 'एकताबद्ध, अझ बलियो संघ।')}</span></footer>
    </div>
    {editing && <RecordEditor collection={editing.collection} entry={editing.entry} existing={entries(data, editing.collection)} t={t} onClose={() => setEditing(null)} onSaved={notifySaved} />}
    {viewing && <SubmissionDetail collection={viewing.collection} entry={viewing.entry} t={t} onClose={() => setViewing(null)} onSaved={notifySaved} onDelete={() => { setDeleteError(''); setDeleting(viewing); }} />}
    {deleting && <Modal title={t('Delete this record?', 'यो अभिलेख हटाउने?')} onClose={() => { if (!busy) setDeleting(null); }} compact><div className="ant-confirm"><div className="ant-delete-symbol"><Trash2 size={24} /></div><p>{t('You are about to delete', 'तपाईं यो अभिलेख हटाउँदै हुनुहुन्छ:')}</p><strong>{entryTitle(deleting.entry, lang)}</strong><p>{t('This will remove the selected record from the workspace and public website.', 'यो छानिएको अभिलेख कार्यक्षेत्र र सार्वजनिक वेबसाइटबाट हटाइनेछ।')}</p>{deleteError && <p className="ant-alert ant-alert-error" role="alert">{deleteError}</p>}<div className="ant-dialog-actions"><button type="button" className="ant-button" disabled={busy} onClick={() => setDeleting(null)}>{t('Cancel', 'रद्द गर्नुहोस्')}</button><button type="button" className="ant-button ant-button-danger" disabled={busy} onClick={() => void remove()}>{busy ? t('Deleting…', 'हटाउँदै…') : t('Delete record', 'अभिलेख हटाउनुहोस्')}</button></div></div></Modal>}
    {toast && <div className="ant-toast" role="status"><Check size={18} /><span>{toast}</span><button type="button" onClick={() => setToast('')} aria-label={t('Dismiss notification', 'सूचना बन्द गर्नुहोस्')}><X size={16} /></button></div>}
  </main>;
}

function Overview({ data, t, lang, navigate }: { data: AdminData; t: Translate; lang: 'en' | 'ne'; navigate: (section: Section) => void }) {
  const content = Object.entries(data).filter(([key]) => !['messages', 'applications', 'settings'].includes(key)).flatMap(([, value]) => value as unknown as Entry[]);
  const newMessages = entries(data, 'messages').filter((entry) => entry.status === 'New').length;
  const newApplications = entries(data, 'applications').filter((entry) => entry.status === 'New').length;
  const drafts = content.filter((entry) => entry.status === 'Draft').length;
  const recent = [...entries(data, 'messages').map((entry) => ({ ...entry, source: 'messages' as Section })), ...entries(data, 'applications').map((entry) => ({ ...entry, source: 'applications' as Section }))].sort((a, b) => new Date(String(b.submittedAt)).getTime() - new Date(String(a.submittedAt)).getTime()).slice(0, 5);
  return <><div className="ant-page-heading ant-overview-heading"><div><span className="ant-eyebrow">{t('YOUR UNION. YOUR VOICE.', 'हाम्रो संघ। हाम्रो आवाज।')}</span><h1>{t('The content desk.', 'सामग्री कार्यक्षेत्र।')}</h1><p>{t('Keep your community informed, connected and moving forward.', 'समुदायलाई सूचित, जोडिएको र अगाडि बढिरहेको राख्नुहोस्।')}</p></div><div className="ant-date"><span>{t('TODAY', 'आज')}</span><strong>{new Date().toLocaleDateString(lang === 'ne' ? 'ne-NP' : 'en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</strong></div></div>
    <div className="ant-metrics">{[{ label: t('Published records', 'प्रकाशित अभिलेख'), value: content.filter((entry) => entry.status !== 'Draft').length, note: t('Across your website', 'वेबसाइटभरि'), icon: FileText, target: 'notices' }, { label: t('Committee members', 'समितिका सदस्य'), value: data.committeeMembers.length, note: t('One connected directory', 'एकीकृत निर्देशिका'), icon: UsersRound, target: 'committeeMembers' }, { label: t('New messages', 'नयाँ सन्देश'), value: newMessages, note: t('Waiting for your review', 'समीक्षाको प्रतीक्षामा'), icon: Mail, target: 'messages' }, { label: t('New applications', 'नयाँ आवेदन'), value: newApplications, note: t('People ready to join', 'आबद्ध हुन तयार'), icon: HeartHandshake, target: 'applications' }].map(({ label, value, note, icon: Icon, target }) => <button type="button" className="ant-metric" key={target} onClick={() => navigate(target as Section)}><span className="ant-metric-top">{label}<Icon size={19} /></span><strong>{value.toLocaleString(lang === 'ne' ? 'ne-NP' : 'en-GB')}</strong><span className="ant-metric-bottom">{note}<ArrowUpRight size={15} /></span></button>)}</div>
    <div className="ant-overview-grid"><section className="ant-panel ant-recent"><header className="ant-panel-heading"><div><span className="ant-eyebrow">{t('FROM YOUR COMMUNITY', 'समुदायबाट')}</span><h2>{t('Latest submissions', 'पछिल्ला विवरण')}</h2></div><span className="ant-count">{data.messages.length + data.applications.length}</span></header>{recent.length ? <div className="ant-submission-list">{recent.map((entry) => <button type="button" className="ant-submission-row" key={`${entry.source}-${entry.id}`} onClick={() => navigate(entry.source)}><span className="ant-submission-icon">{entry.source === 'messages' ? <Mail size={19} /> : <UsersRound size={19} />}</span><span><strong>{entryTitle(entry, lang)}</strong><small>{entry.source === 'messages' ? t('Contact message', 'सम्पर्क सन्देश') : t('Membership application', 'सदस्यता आवेदन')} · {new Date(String(entry.submittedAt)).toLocaleDateString(lang === 'ne' ? 'ne-NP' : 'en-GB')}</small></span><Status value={entry.status} t={t} /><ChevronRight size={16} /></button>)}</div> : <div className="ant-empty"><Mail size={28} /><h3>{t('Your inbox is up to date', 'प्राप्त सन्देश अद्यावधिक छ')}</h3><p>{t('Contact messages and membership applications will appear here.', 'सम्पर्क सन्देश तथा सदस्यता आवेदन यहाँ देखिनेछन्।')}</p></div>}</section>
      <aside className="ant-desk-note"><span className="ant-eyebrow">{t('EDITOR’S NOTE', 'सम्पादकीय सूचना')}</span><h2>{t('Every update builds a connection.', 'हरेक अपडेटले सम्बन्ध जोड्छ।')}</h2><p>{t('Publish in English and Nepali so every member can be part of the conversation.', 'हरेक सदस्यले जानकारी पाउन अंग्रेजी र नेपाली दुवै भाषामा प्रकाशन गर्नुहोस्।')}</p><div className="ant-draft-summary"><span>{t('Drafts in your workspace', 'कार्य क्षेत्रका मस्यौदा')}</span><strong>{drafts}</strong></div><button type="button" className="ant-button ant-button-primary" onClick={() => navigate('notices')}>{t('Manage news & notices', 'समाचार र सूचना व्यवस्थापन')}<ArrowUpRight size={16} /></button></aside></div>
    <section className="ant-panel ant-collection-panel"><header className="ant-panel-heading"><div><span className="ant-eyebrow">{t('MAKE IT CURRENT', 'अद्यावधिक राख्नुहोस्')}</span><h2>{t('Your content at a glance', 'सामग्री एक नजरमा')}</h2></div></header><div className="ant-collection-list">{sections.filter((section) => section.group === 'workspace' && section.id !== 'overview').map(({ id, en, ne, icon: Icon }) => <button type="button" key={id} onClick={() => navigate(id)}><Icon size={19} /><span>{t(en, ne)}</span><strong>{entries(data, id as Collection).length}</strong><ChevronRight size={15} /></button>)}</div></section>
  </>;
}

function Modal({ title, onClose, children, compact = false }: { title: string; onClose: () => void; children: ReactNode; compact?: boolean }) {
  const dialog = useRef<HTMLDivElement>(null);
  const closeRef = useRef(onClose); closeRef.current = onClose;
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const oldOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden';
    dialog.current?.querySelector<HTMLElement>('button, input, select, textarea, a[href]')?.focus();
    const handleKey = (event: KeyboardEvent) => { if (!dialog.current?.contains(document.activeElement)) return; if (event.key === 'Escape') { event.preventDefault(); closeRef.current(); } if (event.key === 'Tab') { const elements = [...dialog.current!.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href]')].filter((node) => node.getClientRects().length); const first = elements[0]; const last = elements[elements.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } };
    document.addEventListener('keydown', handleKey); return () => { document.body.style.overflow = oldOverflow; document.removeEventListener('keydown', handleKey); previous?.focus(); };
  }, []);
  return <div className="ant-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className={`ant-dialog ${compact ? 'ant-dialog-compact' : ''}`} role="dialog" aria-modal="true" aria-label={title} ref={dialog}><header className="ant-dialog-heading"><h2>{title}</h2><button type="button" className="ant-icon-button" onClick={onClose} aria-label="Close / बन्द गर्नुहोस्"><X size={21} /></button></header>{children}</div></div>;
}

function initialRecord(collection: ContentCollection, existing: Entry[]): Entry {
  const record: Entry = { id: collection === 'settings' ? 'site-settings' : collection === 'pages' ? ['about', 'chairperson'].find((id) => !existing.some((item) => item.id === id)) || 'about' : crypto.randomUUID() };
  for (const field of schemas[collection]) { if (field.kind === 'localized' || field.kind === 'body') record[field.key] = { en: '', ne: '' }; else if (field.kind === 'select') record[field.key] = field.options![0]; else if (field.kind === 'number') record[field.key] = 0; else if (field.kind === 'checkbox') record[field.key] = false; else record[field.key] = ''; }
  if (collection !== 'settings') { record.status = 'Draft'; record.order = existing.length; }
  if ('date' in record) record.date = new Date().toISOString().slice(0, 10);
  if (collection === 'committeeMembers') record.accent = 'red';
  if (collection === 'values') record.number = String(existing.length + 1).padStart(2, '0');
  if (collection === 'documents') record.type = 'PDF';
  return record;
}

function RecordEditor({ collection, entry, existing, t, onClose, onSaved }: { collection: ContentCollection; entry: Entry | null; existing: Entry[]; t: Translate; onClose: () => void; onSaved: () => Promise<void> }) {
  const [record, setRecord] = useState<Entry>(() => entry ? structuredClone(entry) : initialRecord(collection, existing));
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState<string | null>(null);
  const [error, setError] = useState('');
  const update = (key: string, value: unknown) => setRecord((current) => ({ ...current, [key]: value }));
  const moduleInfo = sections.find((section) => section.id === collection)!;
  const upload = async (key: string, file: File) => {
    setUploading(key); setError(''); const form = new FormData(); form.append('file', file);
    try { const result = await request<{ url: string; name: string; type: string; size: number }>('/api/admin/uploads', { method: 'POST', body: form }); setRecord((current) => ({ ...current, [key]: result.url, ...(collection === 'documents' && key === 'file' ? { type: result.name.split('.').pop()?.toUpperCase() || result.type, size: result.size >= 1048576 ? `${(result.size / 1048576).toFixed(1)} MB` : `${Math.ceil(result.size / 1024)} KB` } : {}) })); } catch (err) { setError(err instanceof Error ? err.message : t('Upload failed.', 'अपलोड असफल भयो।')); } finally { setUploading(null); }
  };
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); try { await request('/api/admin/content', { method: entry ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ collection, record }) }); await onSaved(); } catch (err) { setError(err instanceof Error ? err.message : t('Could not save the record.', 'अभिलेख सुरक्षित गर्न सकिएन।')); } finally { setSaving(false); } };
  return <Modal title={`${entry ? t('Edit', 'सम्पादन') : t('Add', 'थप्नुहोस्')} · ${t(moduleInfo.en, moduleInfo.ne)}`} onClose={() => { if (!saving && !uploading) onClose(); }}><form onSubmit={save} className="ant-editor-form"><div className="ant-editor-body"><div className="ant-editor-hint"><CircleHelp size={17} /><p>{t('Write both language versions before publishing. Fields marked * are required.', 'प्रकाशनअघि दुवै भाषामा लेख्नुहोस्। * भएका विवरण अनिवार्य छन्।')}</p></div>
      {collection === 'pages' && !entry && <label className="ant-field"><span>{t('Page', 'पृष्ठ')} *</span><select value={record.id} onChange={(event) => update('id', event.target.value)}>{['about', 'chairperson'].filter((id) => !existing.some((item) => item.id === id)).map((id) => <option key={id} value={id}>{id === 'about' ? t('About page', 'हाम्रो बारेमा') : t('Chairperson message', 'अध्यक्षको सन्देश')}</option>)}</select></label>}
      {schemas[collection].map((field) => {
        if (collection === 'galleryItems' && field.key === 'video' && record.type !== 'video') return null;
        const required = !field.optional || (collection === 'galleryItems' && (field.key === 'image' && record.type === 'photo' || field.key === 'video' && record.type === 'video'));
        const value = record[field.key];
        if (field.kind === 'localized' || field.kind === 'body') return <fieldset className="ant-bilingual" key={field.key}><legend>{t(field.en, field.ne)}{required && ' *'}</legend><div className="ant-bilingual-grid">{(['en', 'ne'] as const).map((language) => <label className="ant-field" key={language}><span className="ant-language-label">{language === 'en' ? 'ENGLISH' : 'नेपाली'}</span>{field.kind === 'body' ? <textarea required={required} lang={language} rows={field.key === 'body' ? 8 : 3} value={value && typeof value === 'object' ? String((value as Record<string, unknown>)[language] || '') : ''} onChange={(event) => update(field.key, { ...(typeof value === 'object' && value ? value : {}), [language]: event.target.value })} /> : <input required={required} lang={language} value={value && typeof value === 'object' ? String((value as Record<string, unknown>)[language] || '') : ''} onChange={(event) => update(field.key, { ...(typeof value === 'object' && value ? value : {}), [language]: event.target.value })} />}</label>)}</div></fieldset>;
        if (field.kind === 'checkbox') return <label className="ant-checkbox" key={field.key}><input type="checkbox" checked={Boolean(value)} onChange={(event) => update(field.key, event.target.checked)} /><span>{t(field.en, field.ne)}</span></label>;
        if (field.kind === 'asset') { const url = String(value || ''); const image = field.key === 'image'; const video = field.key === 'video'; return <div className="ant-asset-field" key={field.key}><label className="ant-field" htmlFor={`editor-${field.key}`}><span>{t(field.en, field.ne)}{required && ' *'}</span><input id={`editor-${field.key}`} value={url} required={required} onChange={(event) => update(field.key, event.target.value)} placeholder={video ? 'https://… or /media/…' : '/media/…'} /></label><div className="ant-upload-row"><label className={`ant-upload-button ${uploading ? 'ant-disabled' : ''}`}><Upload size={16} />{uploading === field.key ? t('Uploading…', 'अपलोड हुँदैछ…') : t('Upload file', 'फाइल अपलोड')}<input type="file" disabled={Boolean(uploading) || saving} accept={image ? 'image/jpeg,image/png,image/webp' : video ? 'video/mp4,video/webm' : '.pdf,.jpg,.jpeg,.png,.webp'} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(field.key, file); event.target.value = ''; }} /></label><small>{image ? t('JPG, PNG or WebP · up to 5 MB', 'JPG, PNG वा WebP · 5 MB सम्म') : video ? t('MP4 or WebM · up to 20 MB', 'MP4 वा WebM · 20 MB सम्म') : t('PDF or image · up to 20 MB (images: 5 MB)', 'PDF वा तस्बिर · 20 MB सम्म (तस्बिर: 5 MB)')}</small>{url && !required && <button type="button" className="ant-text-button" onClick={() => update(field.key, '')}>{t('Clear', 'हटाउनुहोस्')}</button>}</div>{url && <div className="ant-asset-preview">{image ? <img src={url} alt={t('Selected image preview', 'छानिएको तस्बिरको पूर्वावलोकन')} /> : video && (url.startsWith('/media/') || /\.(mp4|webm)(\?|$)/i.test(url)) ? <video src={url} controls preload="metadata" /> : <a href={url} target="_blank" rel="noreferrer"><FileText size={18} />{t('Open current file', 'हालको फाइल खोल्नुहोस्')}<ArrowUpRight size={15} /></a>}</div>}</div>; }
        return <label className="ant-field ant-single-field" key={field.key}><span>{t(field.en, field.ne)}{required && ' *'}</span>{field.kind === 'select' ? <select required={required} value={String(value || '')} onChange={(event) => update(field.key, event.target.value)}>{!field.options?.includes(String(value)) && value ? <option value={String(value)}>{String(value)}</option> : null}{field.options!.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input required={required} type={field.kind === 'number' ? 'number' : field.kind === 'email' ? 'email' : field.kind === 'url' ? 'url' : 'text'} step={field.kind === 'number' ? 'any' : undefined} pattern={field.key === 'slug' ? '[a-z0-9]+(?:-[a-z0-9]+)*' : undefined} value={value == null ? '' : String(value)} onChange={(event) => update(field.key, field.kind === 'number' ? event.target.value === '' ? '' : Number(event.target.value) : event.target.value)} />}{field.help && <small>{t(...field.help)}</small>}</label>;
      })}
      {collection !== 'settings' && <div className="ant-publishing"><div><h3>{t('Publishing', 'प्रकाशन')}</h3><p>{t('Drafts are kept private. Published records are visible on the website.', 'मस्यौदा गोप्य रहन्छ। प्रकाशित अभिलेख वेबसाइटमा देखिन्छ।')}</p></div><label className="ant-field"><span>{t('Status', 'अवस्था')}</span><select value={String(record.status || 'Published')} onChange={(event) => update('status', event.target.value)}><option value="Draft">{t('Draft', 'मस्यौदा')}</option><option value="Published">{t('Published', 'प्रकाशित')}</option></select></label><label className="ant-field"><span>{t('Display order', 'प्रदर्शन क्रम')}</span><input type="number" min="0" step="1" value={String(record.order ?? 0)} onChange={(event) => update('order', Number(event.target.value))} /><small>{t('Lower numbers appear first.', 'सानो सङ्ख्या पहिले देखिन्छ।')}</small></label></div>}
      {error && <div className="ant-alert ant-alert-error" role="alert">{error}</div>}
    </div><footer className="ant-editor-footer"><span>{entry ? t('Editing an existing record', 'अवस्थित अभिलेख सम्पादन') : t('New record', 'नयाँ अभिलेख')}</span><div><button type="button" className="ant-button" onClick={onClose} disabled={saving || Boolean(uploading)}>{t('Cancel', 'रद्द गर्नुहोस्')}</button><button type="submit" className="ant-button ant-button-primary" disabled={saving || Boolean(uploading)}>{saving ? <span className="ant-spinner" /> : <Check size={16} />}{saving ? t('Saving…', 'सुरक्षित गर्दै…') : t('Save changes', 'परिवर्तन सुरक्षित गर्नुहोस्')}</button></div></footer></form></Modal>;
}

function SubmissionDetail({ collection, entry, t, onClose, onSaved, onDelete }: { collection: 'messages' | 'applications'; entry: Entry; t: Translate; onClose: () => void; onSaved: () => Promise<void>; onDelete: () => void }) {
  const [status, setStatus] = useState(String(entry.status || 'New'));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const files = Array.isArray(entry.files) ? entry.files as { url: string; name: string; type: string; size: number; field: string }[] : [];
  const save = async () => { setSaving(true); setError(''); try { await request('/api/admin/content', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ collection, record: { ...entry, status } }) }); await onSaved(); } catch (err) { setError(err instanceof Error ? err.message : t('Could not save status.', 'अवस्था सुरक्षित गर्न सकिएन।')); } finally { setSaving(false); } };
  const labels: Record<string, [string, string]> = { id: ['Reference', 'सन्दर्भ'], name: ['Full name', 'पूरा नाम'], email: ['Email', 'इमेल'], phone: ['Phone', 'फोन'], submittedAt: ['Submitted at', 'पेश गरिएको मिति'], subject: ['Subject', 'विषय'], message: ['Message', 'सन्देश'], address: ['Address', 'ठेगाना'], province: ['Province', 'प्रदेश'], district: ['District', 'जिल्ला'], occupation: ['Occupation', 'पेशा'], citizenship: ['Citizenship number', 'नागरिकता नम्बर'], dateOfBirth: ['Date of birth', 'जन्म मिति'], gender: ['Gender', 'लिङ्ग'], workplace: ['Workplace', 'कार्यस्थल'] };
  return <Modal title={collection === 'messages' ? t('Contact message', 'सम्पर्क सन्देश') : t('Membership application', 'सदस्यता आवेदन')} onClose={() => { if (!saving) onClose(); }}><div className="ant-editor-body"><div className="ant-detail-title"><span className="ant-submission-icon"><UsersRound size={25} /></span><div><h3>{String(entry.name || entry.email || entry.id)}</h3><Status value={entry.status} t={t} /></div></div><dl className="ant-details">{Object.entries(entry).filter(([key]) => key !== 'files' && key !== 'status').map(([key, value]) => <div key={key}><dt>{labels[key] ? t(...labels[key]) : key.replace(/([A-Z])/g, ' $1').replace(/^./, (letter) => letter.toUpperCase())}</dt><dd>{typeof value === 'object' ? JSON.stringify(value, null, 2) : typeof value === 'boolean' ? value ? t('Yes', 'हो') : t('No', 'होइन') : String(value ?? '—')}</dd></div>)}</dl><section className="ant-attachments"><h3>{t('Private attachments', 'गोप्य संलग्न फाइल')} <span>{files.length}</span></h3>{files.length ? files.map((file, index) => <a key={`${file.url}-${index}`} href={file.url} target="_blank" rel="noreferrer"><FileText size={20} /><span><strong>{file.name}</strong><small>{file.field} · {file.type} · {Math.ceil(file.size / 1024)} KB</small></span><ArrowUpRight size={17} /></a>) : <p>{t('No files were submitted.', 'कुनै फाइल पेश गरिएको छैन।')}</p>}</section><label className="ant-field ant-single-field"><span>{t('Review status', 'समीक्षा अवस्था')}</span><select value={status} onChange={(event) => setStatus(event.target.value)}>{[...new Set([String(entry.status || 'New'), 'New', 'Reviewed', ...(collection === 'messages' ? ['Resolved'] : ['Approved', 'Rejected'])])].map((value) => <option key={value} value={value}>{statusName(value, t)}</option>)}</select></label>{error && <p className="ant-alert ant-alert-error" role="alert">{error}</p>}</div><footer className="ant-editor-footer"><button type="button" className="ant-text-button ant-danger-text" onClick={onDelete} disabled={saving}><Trash2 size={15} />{t('Delete submission', 'पेश गरिएको विवरण हटाउनुहोस्')}</button><div><button type="button" className="ant-button" onClick={onClose} disabled={saving}>{t('Close', 'बन्द गर्नुहोस्')}</button><button type="button" className="ant-button ant-button-primary" onClick={() => void save()} disabled={saving}>{saving ? t('Saving…', 'सुरक्षित गर्दै…') : t('Save status', 'अवस्था सुरक्षित गर्नुहोस्')}</button></div></footer></Modal>;
}

function Account({ email, t, onLogout, logoutBusy }: { email: string; t: Translate; onLogout: () => Promise<void>; logoutBusy: boolean }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const changePassword = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const fields = new FormData(form); setError(''); setSuccess(''); if (fields.get('newPassword') !== fields.get('confirmPassword')) { setError(t('The new passwords do not match.', 'नयाँ पासवर्डहरू मिलेनन्।')); return; } setBusy(true); try { await request('/api/auth/password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ currentPassword: fields.get('currentPassword'), newPassword: fields.get('newPassword') }) }); form.reset(); setSuccess(t('Password changed. Other sessions have been signed out.', 'पासवर्ड परिवर्तन गरियो। अन्य सत्रहरू बन्द गरिए।')); } catch (err) { setError(err instanceof Error ? err.message : t('Password change failed.', 'पासवर्ड परिवर्तन असफल भयो।')); } finally { setBusy(false); } };
  return <><div className="ant-page-heading"><div><span className="ant-eyebrow">{t('ACCOUNT & SECURITY', 'खाता तथा सुरक्षा')}</span><h1>{t('My account', 'मेरो खाता')}</h1><p>{t('Manage your password and keep a copy of your site content.', 'आफ्नो पासवर्ड व्यवस्थापन र साइट सामग्रीको प्रतिलिपि राख्नुहोस्।')}</p></div></div><div className="ant-account-grid"><section className="ant-panel"><header className="ant-panel-heading"><h2>{t('Change password', 'पासवर्ड परिवर्तन')}</h2><ShieldCheck size={20} /></header><form className="ant-account-form" onSubmit={changePassword}><p>{t('Signed in as', 'लगइन गरिएको खाता')} <strong>{email}</strong></p><label className="ant-field"><span>{t('Current password', 'हालको पासवर्ड')}</span><input name="currentPassword" type="password" autoComplete="current-password" required /></label><label className="ant-field"><span>{t('New password', 'नयाँ पासवर्ड')}</span><input name="newPassword" type="password" autoComplete="new-password" minLength={12} required /><small>{t('Use at least 12 characters.', 'कम्तीमा १२ अक्षर प्रयोग गर्नुहोस्।')}</small></label><label className="ant-field"><span>{t('Confirm new password', 'नयाँ पासवर्ड पुष्टि गर्नुहोस्')}</span><input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} required /></label>{error && <p className="ant-alert ant-alert-error" role="alert">{error}</p>}{success && <p className="ant-alert ant-alert-success" role="status">{success}</p>}<button type="submit" className="ant-button ant-button-primary" disabled={busy}>{busy ? t('Updating…', 'अद्यावधिक हुँदैछ…') : t('Update password', 'पासवर्ड अद्यावधिक')}</button></form></section><div className="ant-account-aside"><section className="ant-panel ant-account-box"><ArrowDownToLine size={24} /><h2>{t('Content backup', 'सामग्रीको ब्याकअप')}</h2><p>{t('Download a JSON copy of your content and submissions for your records.', 'आफ्नो अभिलेखका लागि सामग्री र पेश गरिएका विवरणको JSON प्रतिलिपि डाउनलोड गर्नुहोस्।')}</p><a className="ant-button" href="/api/admin/export" download>{t('Download backup', 'ब्याकअप डाउनलोड')}<ArrowDownToLine size={16} /></a></section><section className="ant-panel ant-account-box"><LogOut size={23} /><h2>{t('End your session', 'सत्र अन्त्य गर्नुहोस्')}</h2><p>{t('Sign out when you finish, especially on a shared computer.', 'विशेष गरी साझा कम्प्युटरमा काम सकेपछि साइन आउट गर्नुहोस्।')}</p><button type="button" className="ant-button" disabled={logoutBusy} onClick={() => void onLogout()}>{logoutBusy ? t('Signing out…', 'साइन आउट हुँदैछ…') : t('Sign out', 'साइन आउट')}</button></section></div></div></>;
}
