'use client';
import Image from 'next/image';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Check, Phone, PlayCircle, Send, X } from '@/components/icons';
import { L, useLanguage } from '@/components/language';
import { useContent } from '@/components/content-provider';
import { EmptyState, SearchField, published } from '@/components/public-ui';
import { text, type CommitteeCategory, type CommitteeMember } from '@/lib/types';
export { MembershipForm } from '@/components/membership-form';
export function MemberIdentity({ member }: { member: CommitteeMember }) {
  const { lang } = useLanguage(); const initials = text(member.name, lang).split(/\s+/).filter(Boolean).slice(0, 2).map(part => [...part][0]).join('');
  return <div className="member-identity">{member.image ? <Image className="member-avatar" src={member.image} alt={text(member.name, lang)} width={68} height={68} sizes="68px" /> : <span className="member-initials" aria-hidden="true">{initials}</span>}<div><h2><L value={member.name} /></h2><p><L value={member.role} /></p><small><L value={member.location} /></small></div></div>;
}
export function CommitteeDirectory({ initialCategory = 'All' }: { initialCategory?: 'All' | CommitteeCategory }) {
  const { lang } = useLanguage(); const all = published(useContent().committeeMembers); const [category, setCategory] = useState<'All' | CommitteeCategory>(initialCategory); const [query, setQuery] = useState('');
  const labels = { All: { en: 'All members', ne: 'सबै सदस्य' }, Central: { en: 'Central', ne: 'केन्द्रीय' }, Province: { en: 'Province', ne: 'प्रदेश' }, District: { en: 'District', ne: 'जिल्ला' }, Unit: { en: 'Unit', ne: 'इकाई' }, International: { en: 'International', ne: 'अन्तर्राष्ट्रिय' } };
  useEffect(() => { setCategory(initialCategory); setQuery(''); }, [initialCategory]);
  const items = all.filter(item => (category === 'All' || item.category === category) && `${item.name.en} ${item.name.ne} ${item.role.en} ${item.role.ne} ${item.location.en} ${item.location.ne}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="filter-bar"><div className="filter-tabs">{(Object.keys(labels) as (keyof typeof labels)[]).map(item => <button key={item} type="button" className={category === item ? 'active' : ''} aria-pressed={category === item} onClick={() => setCategory(item)}><L value={labels[item]} /></button>)}</div><SearchField value={query} change={setQuery} label={{ en: 'Search name, role or location', ne: 'नाम, पद वा स्थान खोज्नुहोस्' }} /></div><p className="result-note" aria-live="polite">{items.length} <L value={{ en: 'members found', ne: 'सदस्य भेटिए' }} /></p>{items.length ? <div className="people-grid">{items.map((member, index) => <article className="person-card" key={member.id}><span className="person-number">{String(index + 1).padStart(2, '0')}</span><MemberIdentity member={member} />{member.phone && <a className="member-phone" href={`tel:${member.phone.replace(/[^+\d]/g, '')}`} aria-label={`${lang === 'ne' ? 'फोन गर्नुहोस्' : 'Call'} ${text(member.name, lang)}`}><Phone size={14} /><span>{member.phone}</span></a>}</article>)}</div> : <EmptyState kind={{ en: 'committee members', ne: 'समिति सदस्य' }} search={Boolean(query)} />}</>;
}
export function GalleryLightbox({ type = 'all' }: { type?: 'all' | 'photo' | 'video' }) {
  const { lang } = useLanguage(); const all = published(useContent().galleryItems); const [filter, setFilter] = useState<'all' | 'photo' | 'video'>(type); const [selected, setSelected] = useState<number | null>(null); const dialog = useRef<HTMLDialogElement>(null); const closeButton = useRef<HTMLButtonElement>(null); const trigger = useRef<HTMLElement | null>(null);
  const items = all.filter(item => (filter === 'all' || item.type === filter) && (item.type !== 'video' || Boolean(item.video))); const current = selected === null ? null : items[selected];
  useEffect(() => { setFilter(type); setSelected(null); }, [type]);
  useEffect(() => { if (selected === null) { if (dialog.current?.open) dialog.current.close(); return; } if (!dialog.current?.open) dialog.current?.showModal(); const frame = window.requestAnimationFrame(() => { if (window.matchMedia('(min-width: 761px)').matches) closeButton.current?.focus(); }); const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { window.cancelAnimationFrame(frame); document.body.style.overflow = previous; }; }, [selected]);
  const close = () => { setSelected(null); trigger.current?.focus(); }; const shift = (delta: number) => setSelected(index => index === null ? null : (index + delta + items.length) % items.length);
  return <>{type === 'all' && <div className="filter-bar"><div className="filter-tabs">{(['all', 'photo', 'video'] as const).map(value => <button type="button" key={value} className={value === filter ? 'active' : ''} aria-pressed={value === filter} onClick={() => setFilter(value)}><L value={value === 'all' ? { en: 'All media', ne: 'सबै सामग्री' } : value === 'photo' ? { en: 'Photos', ne: 'फोटो' } : { en: 'Videos', ne: 'भिडियो' }} /></button>)}</div><span className="result-note">{items.length} <L value={{ en: 'items', ne: 'सामग्री' }} /></span></div>}{items.length ? <div className="gallery-grid">{items.map((item, index) => <button className="gallery-grid-item" type="button" key={item.id} onClick={event => { trigger.current = event.currentTarget; setSelected(index); }} aria-label={`${lang === 'ne' ? 'खोल्नुहोस्' : 'Open'} ${text(item.title, lang)}`}><span className="gallery-photo"><Image src={item.image} alt="" aria-hidden="true" fill sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 33vw" />{item.type === 'video' && <PlayCircle className="gallery-play" size={42} aria-hidden="true" />}</span><span className="gallery-label"><L value={item.title} /><ArrowRight size={18} aria-hidden="true" /></span></button>)}</div> : <EmptyState kind={filter === 'video' ? { en: 'videos', ne: 'भिडियो' } : { en: 'photos', ne: 'फोटो' }} />}<dialog className="lightbox" ref={dialog} onCancel={event => { event.preventDefault(); close(); }} onClick={event => { if (event.target === event.currentTarget) close(); }} onKeyDown={event => { if (event.key === 'ArrowRight') { event.preventDefault(); shift(1); } if (event.key === 'ArrowLeft') { event.preventDefault(); shift(-1); } }}>{current && <div className="lightbox-inner"><div className="lightbox-top"><span>{(selected || 0) + 1} / {items.length}</span><button ref={closeButton} className="icon-button" type="button" onClick={close} aria-label={lang === 'ne' ? 'बन्द गर्नुहोस्' : 'Close preview'}><X size={24} /></button></div>{current.type === 'video' && current.video ? <video key={current.video} src={current.video} poster={current.image} controls playsInline preload="metadata" /> : <Image src={current.image} alt={text(current.title, lang)} width={1500} height={1000} sizes="95vw" />}<div className="lightbox-caption"><p><L value={current.title} /></p><div><button className="icon-button" type="button" onClick={() => shift(-1)} aria-label={lang === 'ne' ? 'अघिल्लो' : 'Previous image'}><ArrowLeft size={21} aria-hidden="true" /></button><button className="icon-button" type="button" onClick={() => shift(1)} aria-label={lang === 'ne' ? 'अर्को' : 'Next image'}><ArrowRight size={21} aria-hidden="true" /></button></div></div></div>}</dialog></>;
}
export function FormSuccess({ title, id, onReset }: { title: { en: string; ne: string }; id: string; onReset: () => void }) { return <div className="success-box" role="status"><span className="success-icon"><Check size={28} /></span><h3><L value={title} /></h3><p><L value={{ en: 'Your submission has been received by the union office.', ne: 'तपाईंको विवरण संघ कार्यालयमा प्राप्त भएको छ।' }} /></p><p className="submission-reference"><L value={{ en: 'Reference', ne: 'सन्दर्भ' }} />: {id}</p><button className="button outline" type="button" onClick={onReset}><L value={{ en: 'Start a new submission', ne: 'नयाँ विवरण पठाउनुहोस्' }} /></button></div>; }
export function ContactForm() {
  const { lang } = useLanguage(); const [result, setResult] = useState(''); const [pending, setPending] = useState(false); const [error, setError] = useState('');
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); setError(''); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const json = await response.json(); if (!response.ok || !json.ok) throw new Error(json.error || 'Submission failed.'); setResult(json.id); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Please try again.'); } finally { setPending(false); } };
  if (result) return <FormSuccess title={{ en: 'Thank you for getting in touch.', ne: 'सम्पर्क गर्नुभएकोमा धन्यवाद।' }} id={result} onReset={() => setResult('')} />;
  return <form className="form-grid" onSubmit={submit} aria-busy={pending}><div className="field"><label htmlFor="contact-name"><L value={{ en: 'Full name', ne: 'पूरा नाम' }} /> *</label><input autoComplete="name" required id="contact-name" name="name" maxLength={150} /></div><div className="field"><label htmlFor="contact-email"><L value={{ en: 'Email address', ne: 'इमेल ठेगाना' }} /> *</label><input autoComplete="email" required type="email" id="contact-email" name="email" maxLength={254} /></div><div className="field"><label htmlFor="contact-phone"><L value={{ en: 'Phone number', ne: 'फोन नम्बर' }} /> *</label><input autoComplete="tel" type="tel" required id="contact-phone" name="phone" maxLength={30} /></div><div className="field"><label htmlFor="contact-subject"><L value={{ en: 'Subject (optional)', ne: 'विषय (वैकल्पिक)' }} /></label><input id="contact-subject" name="subject" maxLength={200} /></div><div className="field full"><label htmlFor="contact-message"><L value={{ en: 'Your message', ne: 'तपाईंको सन्देश' }} /> *</label><textarea required id="contact-message" name="message" rows={5} maxLength={10000} placeholder={lang === 'ne' ? 'हामी कसरी सहयोग गर्न सक्छौं?' : 'How can we help?'} /></div>{error && <div className="form-error full" role="alert">{lang === 'ne' ? 'सन्देश पठाउन सकिएन। विवरण जाँचेर फेरि प्रयास गर्नुहोस्।' : error}</div>}<div className="field full"><button className="button primary" type="submit" disabled={pending}><L value={pending ? { en: 'Sending…', ne: 'पठाइँदै छ…' } : { en: 'Send message', ne: 'सन्देश पठाउनुहोस्' }} /><Send size={16} /></button></div></form>;
}
