'use client';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight } from '@/components/icons';
import { L, useLanguage } from '@/components/language';
import { useContent } from '@/components/content-provider';
import { CommitteeDirectory, GalleryLightbox } from '@/components/interactive-public';
import { BodyText, DocumentList, EmptyState, NoticeList, OfficeAside, PageHero, published } from '@/components/public-ui';
import { text, type CommitteeCategory, type Localized } from '@/lib/types';
export function LegacyDirectoryPage({ category, title, description }: { category: CommitteeCategory; title: Localized; description: Localized }) { return <main><PageHero title={title} description={description} section={{ en: 'Committee directory', ne: 'समिति निर्देशिका' }} /><section className="section"><div className="container"><CommitteeDirectory initialCategory={category} /></div></section></main>; }
export function OrganizationChartPage() {
  const members = published(useContent().committeeMembers); const nodes: { category: CommitteeCategory; title: Localized; href: string }[] = [ { category: 'Central', title: { en: 'Central committee', ne: 'केन्द्रीय समिति' }, href: '/render_central_members' }, { category: 'Province', title: { en: 'Province committees', ne: 'प्रदेश समिति' }, href: '/render_province_members' }, { category: 'District', title: { en: 'District committees', ne: 'जिल्ला समिति' }, href: '/render_district_members' }, { category: 'Unit', title: { en: 'Unit committees', ne: 'इकाई समिति' }, href: '/render_unit_members' } ];
  return <main><PageHero title={{ en: 'Our organizational structure.', ne: 'हाम्रो संगठनात्मक संरचना।' }} section={{ en: 'Organization chart', ne: 'संगठनात्मक चार्ट' }} description={{ en: 'Explore the union’s central, provincial, district, unit and international committees.', ne: 'संघका केन्द्रीय, प्रदेश, जिल्ला, इकाई र अन्तर्राष्ट्रिय समिति हेर्नुहोस्।' }} /><section className="section"><div className="container chart-layout"><div className="organization-chart"><div className="chart-heading">ANTWU<span><L value={{ en: 'All Nepal Transport Workers’ Union', ne: 'अखिल नेपाल यातायात मजदुर संघ' }} /></span></div><ol className="chart-tree">{nodes.map((node, index) => <li key={node.category}><Link href={node.href} className="chart-node"><span className="chart-order">0{index + 1}</span><strong><L value={node.title} /></strong><span className="chart-count">{members.filter(item => item.category === node.category).length} <L value={{ en: 'listed members', ne: 'सूचीकृत सदस्य' }} /></span><ArrowRight size={19} /></Link></li>)}</ol><Link className="chart-international" href="/render_international_members"><div><span className="eyebrow"><L value={{ en: 'International representation', ne: 'अन्तर्राष्ट्रिय प्रतिनिधित्व' }} /></span><h2><L value={{ en: 'International committee', ne: 'अन्तर्राष्ट्रिय समिति' }} /></h2></div><ArrowRight size={23} aria-hidden="true" /></Link></div><OfficeAside /></div></section></main>;
}
export function ChairpersonPage() { const page = published(useContent().pages).find(item => item.id === 'chairperson'); const { lang } = useLanguage(); return <main><PageHero title={page?.title || { en: 'Message from the chairperson', ne: 'अध्यक्षको सन्देश' }} section={{ en: 'Chairperson', ne: 'अध्यक्ष' }} /><section className="section"><div className="container two-col"><article>{page?.image && <Image className="article-image" src={page.image} alt={text(page.title, lang)} width={850} height={650} sizes="(max-width: 760px) 100vw, 60vw" />}{page?.body.en || page?.body.ne ? <BodyText value={page.body} /> : <EmptyState kind={{ en: 'chairperson’s message', ne: 'अध्यक्षको सन्देश' }} />}<Link href="/render_central_members" className="text-link"><L value={{ en: 'View central committee', ne: 'केन्द्रीय समिति हेर्नुहोस्' }} /><ArrowRight size={17} /></Link></article><OfficeAside /></div></section></main>; }
export function DocumentCategoryPage({ category, title, description }: { category: string; title: Localized; description: Localized }) { return <main><PageHero title={title} description={description} section={{ en: 'Documents', ne: 'कागजात' }} /><section className="section"><div className="container"><DocumentList category={category} /><div className="below-archive-link"><Link className="text-link" href="/documents"><L value={{ en: 'Browse all documents', ne: 'सबै कागजात हेर्नुहोस्' }} /><ArrowRight size={17} /></Link></div></div></section></main>; }
const titles: Record<string, Localized> = { Notice: { en: 'Notices', ne: 'सूचना' }, 'Press release': { en: 'Press releases', ne: 'प्रेस विज्ञप्ति' }, Tender: { en: 'Tenders', ne: 'बोलपत्र' }, News: { en: 'News', ne: 'समाचार' }, Other: { en: 'Other downloads', ne: 'अन्य डाउनलोड' } };
export function DownloadCategoryPage({ category }: { category: string }) { return <main><PageHero title={titles[category] || titles.Other} section={{ en: 'Updates & downloads', ne: 'सूचना र डाउनलोड' }} description={{ en: 'Published information and resources from the union office.', ne: 'संघ कार्यालयबाट प्रकाशित जानकारी र सामग्री।' }} /><section className="section"><div className="container two-col"><div>{category === 'Other' ? <DocumentList category="Other" /> : <NoticeList category={category} />}<div className="below-archive-link"><Link href="/updates" className="text-link"><L value={{ en: 'See all updates', ne: 'सबै सूचना हेर्नुहोस्' }} /><ArrowRight size={17} /></Link></div></div><OfficeAside /></div></section></main>; }
export function GalleryCategoryPage({ type }: { type: 'photo' | 'video' }) { return <main><PageHero title={type === 'photo' ? { en: 'Photo gallery', ne: 'फोटो ग्यालरी' } : { en: 'Video gallery', ne: 'भिडियो ग्यालरी' }} section={{ en: 'Gallery', ne: 'ग्यालरी' }} description={{ en: 'People and moments from the ANTWU archive.', ne: 'अन्तुको अभिलेखबाट मानिस र क्षणहरू।' }} /><section className="section"><div className="container"><GalleryLightbox type={type} /><div className="below-archive-link"><Link href="/gallery" className="text-link"><L value={{ en: 'View all media', ne: 'सबै सामग्री हेर्नुहोस्' }} /><ArrowRight size={17} /></Link></div></div></section></main>; }
export function StatisticsPage() { const { stats, committeeMembers } = useContent(); const records = published(stats); const members = published(committeeMembers); return <main><PageHero title={{ en: 'Our union in numbers.', ne: 'तथ्याङ्कमा हाम्रो संघ।' }} section={{ en: 'Statistics', ne: 'तथ्याङ्क' }} description={{ en: 'Published statistics and the current committee directory.', ne: 'प्रकाशित तथ्याङ्क र हालको समिति निर्देशिका।' }} /><section className="section"><div className="container"><div className="statistics-list">{records.map(item => <article key={item.id}><strong>{item.id === 'central-count' ? members.filter(member => member.category === 'Central').length : item.value}{item.suffix}</strong><h2><L value={item.label} /></h2></article>)}</div>{!records.length && <EmptyState kind={{ en: 'statistics', ne: 'तथ्याङ्क' }} />}<div className="below-archive-link"><Link href="/committee" className="text-link"><L value={{ en: 'Explore the member directory', ne: 'सदस्य निर्देशिका हेर्नुहोस्' }} /><ArrowRight size={17} /></Link></div></div></section></main>; }
