'use client';
import { useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { ArrowRight, Check } from '@/components/icons';
import { L, useLanguage } from '@/components/language';
import type { Localized } from '@/lib/types';
const provinceLabels: Record<string, Localized> = { Koshi: { en: 'Koshi', ne: 'कोशी' }, Madhesh: { en: 'Madhesh', ne: 'मधेश' }, Bagmati: { en: 'Bagmati', ne: 'बागमती' }, Gandaki: { en: 'Gandaki', ne: 'गण्डकी' }, Lumbini: { en: 'Lumbini', ne: 'लुम्बिनी' }, Karnali: { en: 'Karnali', ne: 'कर्णाली' }, Sudurpashchim: { en: 'Sudurpashchim', ne: 'सुदूरपश्चिम' } };
const districtRows: Record<string, string> = {
  Koshi: 'Bhojpur|भोजपुर,Dhankuta|धनकुटा,Ilam|इलाम,Jhapa|झापा,Khotang|खोटाङ,Morang|मोरङ,Okhaldhunga|ओखलढुङ्गा,Panchthar|पाँचथर,Sankhuwasabha|सङ्खुवासभा,Solukhumbu|सोलुखुम्बु,Sunsari|सुनसरी,Taplejung|ताप्लेजुङ,Terhathum|तेह्रथुम,Udayapur|उदयपुर',
  Madhesh: 'Bara|बारा,Dhanusha|धनुषा,Mahottari|महोत्तरी,Parsa|पर्सा,Rautahat|रौतहट,Saptari|सप्तरी,Sarlahi|सर्लाही,Siraha|सिराहा',
  Bagmati: 'Bhaktapur|भक्तपुर,Chitwan|चितवन,Dhading|धादिङ,Dolakha|दोलखा,Kathmandu|काठमाडौं,Kavrepalanchok|काभ्रेपलाञ्चोक,Lalitpur|ललितपुर,Makwanpur|मकवानपुर,Nuwakot|नुवाकोट,Ramechhap|रामेछाप,Rasuwa|रसुवा,Sindhuli|सिन्धुली,Sindhupalchok|सिन्धुपाल्चोक',
  Gandaki: 'Baglung|बागलुङ,Gorkha|गोरखा,Kaski|कास्की,Lamjung|लमजुङ,Manang|मनाङ,Mustang|मुस्ताङ,Myagdi|म्याग्दी,Nawalpur|नवलपुर,Parbat|पर्वत,Syangja|स्याङ्जा,Tanahun|तनहुँ',
  Lumbini: 'Arghakhanchi|अर्घाखाँची,Banke|बाँके,Bardiya|बर्दिया,Dang|दाङ,Gulmi|गुल्मी,Kapilvastu|कपिलवस्तु,Palpa|पाल्पा,Pyuthan|प्युठान,Rolpa|रोल्पा,Rukum East|रुकुम पूर्व,Rupandehi|रुपन्देही',
  Karnali: 'Dailekh|दैलेख,Dolpa|डोल्पा,Humla|हुम्ला,Jajarkot|जाजरकोट,Jumla|जुम्ला,Kalikot|कालीकोट,Mugu|मुगु,Rukum West|रुकुम पश्चिम,Salyan|सल्यान,Surkhet|सुर्खेत',
  Sudurpashchim: 'Achham|अछाम,Baitadi|बैतडी,Bajhang|बझाङ,Bajura|बाजुरा,Dadeldhura|डडेलधुरा,Darchula|दार्चुला,Doti|डोटी,Kailali|कैलाली,Kanchanpur|कञ्चनपुर',
};
type InputProps = { name: string; label: Localized; required?: boolean; type?: string; full?: boolean; hint?: Localized; placeholder?: string };
function Field({ name, label, required, type = 'text', full, hint, placeholder }: InputProps) { const autoComplete = name === 'name' ? 'name' : name === 'email' ? 'email' : name === 'phone' ? 'tel' : name === 'perma_address' ? 'street-address' : 'off'; return <div className={`field ${full ? 'full' : ''}`}><label htmlFor={`member-${name}`}><L value={label} />{required && ' *'}</label><input autoComplete={autoComplete} id={`member-${name}`} name={name} required={required} type={type} maxLength={type === 'email' ? 254 : 250} placeholder={placeholder} aria-describedby={hint ? `help-${name}` : undefined} />{hint && <small id={`help-${name}`} className="field-help"><L value={hint} /></small>}</div>; }
function Select({ name, label, options, required }: { name: string; label: Localized; options: [string, string, string][]; required?: boolean }) { const { lang } = useLanguage(); return <div className="field"><label htmlFor={`member-${name}`}><L value={label} />{required && ' *'}</label><select id={`member-${name}`} name={name} required={required} defaultValue=""><option value="">{lang === 'ne' ? 'छान्नुहोस्' : 'Select an option'}</option>{options.map(([value, en, ne]) => <option key={value} value={value}>{lang === 'ne' ? ne : en}</option>)}</select></div>; }
function YesNo({ name, label }: { name: string; label: Localized }) { return <fieldset className="field radio-field"><legend><L value={label} /></legend><div><label><input type="radio" name={name} value="Yes" /><L value={{ en: 'Yes', ne: 'छ' }} /></label><label><input type="radio" name={name} value="No" /><L value={{ en: 'No', ne: 'छैन' }} /></label></div></fieldset>; }
export function MembershipForm() {
  const { lang } = useLanguage(); const [step, setStep] = useState(0); const [province, setProvince] = useState(''); const [district, setDistrict] = useState(''); const [result, setResult] = useState(''); const [pending, setPending] = useState(false); const [error, setError] = useState(''); const [files, setFiles] = useState<Record<string, string[]>>({});
  const form = useRef<HTMLFormElement>(null); const stepTitle = useRef<HTMLHeadingElement>(null);
  const steps = [{ en: 'Your details', ne: 'तपाईंको विवरण' }, { en: 'Work & membership', ne: 'काम र सदस्यता' }, { en: 'Documents', ne: 'कागजात' }];
  const validate = (index: number) => { const controls = form.current?.querySelectorAll<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(`[data-step="${index}"] input, [data-step="${index}"] select, [data-step="${index}"] textarea`); const invalid = [...(controls || [])].find(field => !field.checkValidity()); if (invalid) { setStep(index); requestAnimationFrame(() => { invalid.focus(); invalid.reportValidity(); }); return false; } return true; };
  const go = (next: number) => { if (next < step || validate(step)) { setStep(next); setError(''); requestAnimationFrame(() => stepTitle.current?.focus()); } };
  const selectFiles = (event: ChangeEvent<HTMLInputElement>) => { const input = event.target; const list = [...(input.files || [])]; const max = input.multiple ? 5 : 1; const accepted = input.name === 'photo' ? ['image/jpeg', 'image/png', 'image/webp'] : ['image/jpeg', 'image/png', 'image/webp', 'application/pdf']; const invalid = list.length > max || list.some(file => file.size > 5 * 1024 * 1024 || !accepted.includes(file.type)); input.setCustomValidity(invalid ? (lang === 'ne' ? 'अनुमत फाइल छान्नुहोस्: प्रत्येक बढीमा ५ MB, परिचयका बढीमा ५ फाइल।' : 'Choose an accepted file type, up to 5 MB each and up to 5 identity files.') : ''); if (invalid) input.reportValidity(); setFiles(current => ({ ...current, [input.name]: list.map(file => file.name) })); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (step < 2) { go(step + 1); return; } for (let index = 0; index < 3; index++) if (!validate(index)) return; const data = new FormData(event.currentTarget); setPending(true); setError(''); try { const response = await fetch('/api/membership', { method: 'POST', body: data }); const json = await response.json(); if (!response.ok || !json.ok) throw new Error(json.error || 'Application could not be submitted.'); setResult(json.id); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Please try again.'); } finally { setPending(false); } };
  if (result) return <div className="success-box" role="status"><span className="success-icon"><Check size={28} /></span><h3><L value={{ en: 'Application received.', ne: 'आवेदन प्राप्त भयो।' }} /></h3><p><L value={{ en: 'The union office has received your application for review.', ne: 'संघ कार्यालयमा समीक्षाका लागि तपाईंको आवेदन प्राप्त भएको छ।' }} /></p><p className="submission-reference"><L value={{ en: 'Reference', ne: 'सन्दर्भ' }} />: {result}</p><button type="button" className="button outline" onClick={() => { setResult(''); setStep(0); setProvince(''); setDistrict(''); setFiles({}); }}><L value={{ en: 'New application', ne: 'नयाँ आवेदन' }} /></button></div>;
  return <div className="membership-flow"><ol className="membership-tabs" aria-label={lang === 'ne' ? 'आवेदनका चरण' : 'Application steps'}>{steps.map((item, index) => <li key={item.en}><button type="button" disabled={index > step || pending} className={index === step ? 'active' : index < step ? 'complete' : ''} aria-current={index === step ? 'step' : undefined} onClick={() => go(index)}><span>{index < step ? <Check size={14} /> : index + 1}</span><L value={item} /></button></li>)}</ol><div className="membership-progress" aria-hidden="true"><span style={{ width: `${((step + 1) / 3) * 100}%` }} /></div><h3 ref={stepTitle} tabIndex={-1} className="membership-step-heading"><L value={steps[step]} /></h3><p className="form-note"><L value={{ en: 'Fields marked * are required.', ne: '* चिन्ह भएका विवरण अनिवार्य छन्।' }} /></p><form className="form-grid" noValidate onSubmit={submit} ref={form} aria-busy={pending}>
    <fieldset className={`membership-step ${step === 0 ? 'is-active' : ''}`} hidden={step !== 0} data-step="0" disabled={pending}><legend className="sr-only"><L value={steps[0]} /></legend><Field name="name" label={{ en: 'Full name', ne: 'पूरा नाम' }} required /><Field name="email" label={{ en: 'Email address', ne: 'इमेल ठेगाना' }} type="email" /><Field name="phone" label={{ en: 'Phone number', ne: 'फोन नम्बर' }} type="tel" required /><Field name="parent_name" label={{ en: 'Parent’s name', ne: 'बुबा वा आमाको नाम' }} /><Field name="perma_address" label={{ en: 'Permanent address', ne: 'स्थायी ठेगाना' }} required /><Field name="temp_address" label={{ en: 'Temporary address', ne: 'अस्थायी ठेगाना' }} /><Select name="marital_status" label={{ en: 'Marital status', ne: 'वैवाहिक स्थिति' }} options={[[ 'Married', 'Married', 'विवाहित' ], [ 'Unmarried', 'Unmarried', 'अविवाहित' ]]} /><Select name="blood_group" label={{ en: 'Blood group', ne: 'रक्त समूह' }} options={['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'].map(value => [value, value, value])} /><YesNo name="social_security" label={{ en: 'Social security coverage', ne: 'सामाजिक सुरक्षा' }} /><Select name="edu_level" label={{ en: 'Education level', ne: 'शिक्षा स्तर' }} options={[[ 'School Level', 'School level', 'विद्यालय तह' ], [ '+2', 'Higher secondary (+2)', 'उच्च माध्यमिक (+२)' ], [ 'Bachelors', 'Bachelor’s', 'स्नातक' ], [ 'Masters', 'Master’s', 'स्नातकोत्तर' ], [ 'PhD', 'PhD', 'विद्यावारिधि' ]]} /></fieldset>
    <fieldset className={`membership-step ${step === 1 ? 'is-active' : ''}`} hidden={step !== 1} data-step="1" disabled={pending}><legend className="sr-only"><L value={steps[1]} /></legend><Field name="committee" label={{ en: 'Committee', ne: 'समिति' }} required /><Field name="position" label={{ en: 'Position', ne: 'पद' }} /><div className="field"><label htmlFor="member-work_province"><L value={{ en: 'Work province', ne: 'कार्य प्रदेश' }} /> *</label><select id="member-work_province" name="work_province" required value={province} onChange={event => { setProvince(event.target.value); setDistrict(''); }}><option value="">{lang === 'ne' ? 'प्रदेश छान्नुहोस्' : 'Select province'}</option>{Object.entries(provinceLabels).map(([value, label]) => <option key={value} value={value}>{label[lang]}</option>)}</select></div><div className="field"><label htmlFor="member-district"><L value={{ en: 'District', ne: 'जिल्ला' }} /> *</label><select id="member-district" name="district" required value={district} onChange={event => setDistrict(event.target.value)}><option value="">{lang === 'ne' ? 'जिल्ला छान्नुहोस्' : 'Select district'}</option>{(districtRows[province] || '').split(',').filter(Boolean).map(row => { const [en, ne] = row.split('|'); return <option key={en} value={en}>{lang === 'ne' ? ne : en}</option>; })}</select></div><Field name="work_route" label={{ en: 'Work area / route', ne: 'कार्य क्षेत्र / रुट' }} full /><YesNo name="min_labor" label={{ en: 'Receiving minimum wage', ne: 'न्यूनतम पारिश्रमिक प्राप्त भएको' }} /><Select name="levi" label={{ en: 'Levy rate', ne: 'लेवी दर' }} required options={[[ 'साधरण - 30', 'General — 30', 'साधारण — ३०' ], [ 'इकाइ - 50', 'Unit — 50', 'इकाइ — ५०' ], [ 'जिल्ला - 100', 'District — 100', 'जिल्ला — १००' ], [ 'प्रदेश - 200', 'Province — 200', 'प्रदेश — २००' ], [ 'केन्द्र - 500', 'Central — 500', 'केन्द्र — ५००' ]]} /><Field name="old_membership" label={{ en: 'Previous membership date (optional)', ne: 'पुरानो सदस्यता मिति (वैकल्पिक)' }} placeholder="YYYY-MM-DD" hint={{ en: 'Enter the Nepali date (B.S.), if applicable.', ne: 'लागू भएमा नेपाली मिति (वि.सं.) लेख्नुहोस्।' }} /><Field name="issue_date" label={{ en: 'Form issue date (B.S.)', ne: 'फारम जारी मिति (वि.सं.)' }} required placeholder="YYYY-MM-DD" hint={{ en: 'Enter the issue date in year-month-day format.', ne: 'साल-महिना-दिनको ढाँचामा मिति लेख्नुहोस्।' }} /></fieldset>
    <fieldset className={`membership-step ${step === 2 ? 'is-active' : ''}`} hidden={step !== 2} data-step="2" disabled={pending}><legend className="sr-only"><L value={steps[2]} /></legend><Field name="id_number" label={{ en: 'Citizenship or driving licence number', ne: 'नागरिकता वा सवारी चालक अनुमतिपत्र नम्बर' }} required full />{[{ name: 'id_image[]', id: 'identity', title: { en: 'Citizenship / licence documents', ne: 'नागरिकता / अनुमतिपत्रका कागजात' }, required: true, multiple: true }, { name: 'photo', id: 'photo', title: { en: 'Your photo', ne: 'तपाईंको फोटो' }, required: true, multiple: false }, { name: 'receipt', id: 'receipt', title: { en: 'Payment receipt (if paid at the office)', ne: 'भुक्तानी रसिद (कार्यालयमा तिरेको भए)' }, required: false, multiple: false }].map(item => <div className="field full upload-field" key={item.id}><label htmlFor={`member-${item.id}`}><L value={item.title} />{item.required && ' *'}</label><input id={`member-${item.id}`} name={item.name} type="file" accept={item.name === 'photo' ? 'image/jpeg,image/png,image/webp' : 'image/jpeg,image/png,image/webp,application/pdf'} multiple={item.multiple} required={item.required} onChange={selectFiles} aria-describedby={`file-help-${item.id}`} /><small className="field-help" id={`file-help-${item.id}`}><L value={item.name === 'photo' ? { en: 'JPEG, PNG or WebP · up to 5 MB', ne: 'JPEG, PNG वा WebP · बढीमा ५ MB' } : { en: `JPEG, PNG, WebP or PDF · up to 5 MB each${item.multiple ? ' · maximum 5 files' : ''}`, ne: `JPEG, PNG, WebP वा PDF · प्रत्येक बढीमा ५ MB${item.multiple ? ' · बढीमा ५ फाइल' : ''}` }} /></small>{files[item.name]?.length > 0 && <ul className="file-preview-list">{files[item.name].map((name, index) => <li key={`${name}-${index}`}><Check size={14} />{name}</li>)}</ul>}</div>)}<p className="form-note full"><L value={{ en: 'Please review your details before submitting. The union office will use these documents to process your membership application.', ne: 'बुझाउनुअघि विवरण जाँच गर्नुहोस्। संघ कार्यालयले यी कागजात सदस्यता आवेदन प्रक्रियाका लागि प्रयोग गर्नेछ।' }} /></p></fieldset>
    {error && <div className="form-error full" role="alert">{lang === 'ne' ? 'आवेदन पठाउन सकिएन। विवरण र फाइल जाँचेर फेरि प्रयास गर्नुहोस्।' : error}</div>}<div className="membership-actions full"><button type="button" className="button outline" disabled={step === 0 || pending} onClick={() => go(step - 1)}><L value={{ en: 'Previous', ne: 'अघिल्लो' }} /></button>{step < 2 ? <button type="button" className="button primary" onClick={() => go(step + 1)}><L value={{ en: 'Continue', ne: 'अगाडि बढ्नुहोस्' }} /><ArrowRight size={17} /></button> : <button className="button primary" type="submit" disabled={pending}><L value={pending ? { en: 'Submitting…', ne: 'पठाइँदै छ…' } : { en: 'Submit application', ne: 'आवेदन बुझाउनुहोस्' }} /><Check size={17} /></button>}</div></form></div>;
}
