'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowRight, FileText, Mail, MapPin, Phone, Search } from '@/components/icons';
import { L, useLanguage } from '@/components/language';
import { useContent } from '@/components/content-provider';
import { documentCategoryLabels, noticeCategoryLabels, text, type Localized, type Notice } from '@/lib/types';
export const published = <T extends { status?: string }>(items: T[]) => items.filter(item => item.status !== 'Draft');
export function PageHero({ title, description, section, number = 'ANTWU' }: { title: Localized; description?: Localized; section?: Localized; number?: string }) {
  return <section className="page-hero"><div className="container"><div className="breadcrumb"><Link href="/"><L value={{ en: 'Home', ne: 'गृहपृष्ठ' }} /></Link><span>/</span><L value={section || title} /></div><div className="page-hero-grid"><div><h1><L value={title} /></h1>{description && <p><L value={description} /></p>}</div><span className="page-index" aria-hidden="true">{number}</span></div></div></section>;
}
export function SectionHeading({ index, title, eyebrow, href, link }: { index?: string; title: Localized; eyebrow?: Localized; href?: string; link?: Localized }) {
  return <div className="section-head"><div>{eyebrow && <span className="eyebrow">{index && <span className="section-index">{index}</span>}<L value={eyebrow} /></span>}<h2><L value={title} /></h2></div>{href && <Link href={href} className="text-link"><L value={link || { en: 'View all', ne: 'सबै हेर्नुहोस्' }} /><ArrowRight size={17} /></Link>}</div>;
}
export function EmptyState({ kind = { en: 'records', ne: 'अभिलेख' }, search = false, compact = false }: { kind?: Localized; search?: boolean; compact?: boolean }) {
  const { lang } = useLanguage();
  return <div className={`empty-state ${compact ? 'compact' : ''}`}><span className="empty-icon"><FileText size={25} strokeWidth={1.3} /></span><div><h2>{search ? (lang === 'ne' ? 'खोजीसँग मिल्ने सामग्री भेटिएन' : 'No matching results') : (lang === 'ne' ? `${kind.ne} अहिले उपलब्ध छैन` : `No ${kind.en} published yet`)}</h2><p>{search ? <L value={{ en: 'Try another search or choose a different category.', ne: 'अर्को शब्द खोज्नुहोस् वा फरक वर्ग छान्नुहोस्।' }} /> : <L value={{ en: 'Published information will appear here. For an existing record or an enquiry, please contact the union office.', ne: 'प्रकाशित जानकारी यहाँ देखिनेछ। पुराना अभिलेख वा सोधपुछका लागि संघ कार्यालयमा सम्पर्क गर्नुहोस्।' }} />}</p>{!search && <Link href="/contact" className="text-link"><L value={{ en: 'Contact the office', ne: 'कार्यालयमा सम्पर्क गर्नुहोस्' }} /><ArrowRight size={15} /></Link>}</div></div>;
}
export function BodyText({ value, className = '' }: { value: Localized; className?: string }) { const { lang } = useLanguage(); return <div className={`prose ${className}`}>{text(value, lang).split(/\n\s*\n/).filter(Boolean).map((part, index) => <p key={index}>{part}</p>)}</div>; }
export function SearchField({ value, change, label }: { value: string; change: (value: string) => void; label: Localized }) { const { lang } = useLanguage(); return <label className="search-field"><Search size={18} aria-hidden="true" /><span className="sr-only">{text(label, lang)}</span><input type="search" value={value} onChange={event => change(event.target.value)} placeholder={text(label, lang)} /></label>; }
export function DocumentList({ category, filters = false }: { category?: string; filters?: boolean }) {
  const all = published(useContent().documents); const { lang } = useLanguage(); const [selected, setSelected] = useState('All'); const [query, setQuery] = useState('');
  const items = all.filter(item => (!category || item.category === category) && (selected === 'All' || item.category === selected) && `${item.title.en} ${item.title.ne}`.toLowerCase().includes(query.toLowerCase()));
  const categories = [...new Set(['Acts & regulations', 'Directives', 'Publications', ...all.map(item => item.category)])];
  return <>{filters && <div className="filter-bar"><div className="filter-tabs"><button type="button" className={selected === 'All' ? 'active' : ''} aria-pressed={selected === 'All'} onClick={() => setSelected('All')}><L value={{ en: 'All documents', ne: 'सबै कागजात' }} /></button>{categories.map(item => <button key={item} type="button" aria-pressed={selected === item} className={selected === item ? 'active' : ''} onClick={() => setSelected(item)}>{documentCategoryLabels[item] ? text(documentCategoryLabels[item], lang) : item}</button>)}</div><SearchField value={query} change={setQuery} label={{ en: 'Search documents', ne: 'कागजात खोज्नुहोस्' }} /></div>}{items.length ? <div className="document-list">{items.map(item => <article className="document-row" key={item.id}><span className={`file-icon ${item.image ? 'file-icon-image' : ''}`}>{item.image ? <Image className="document-thumb" src={item.image} alt="" aria-hidden="true" width={100} height={108} sizes="50px" /> : <FileText size={25} aria-hidden="true" />}<small>{item.type}</small></span><div className="document-copy"><span className="doc-category">{documentCategoryLabels[item.category] ? text(documentCategoryLabels[item.category], lang) : item.category}</span><h2><L value={item.title} /></h2><p>{[item.date, item.size].filter(Boolean).join(' · ')}</p>{item.description && <p><L value={item.description} /></p>}</div>{item.file ? <a className="text-link" href={item.file} download><L value={{ en: 'Download', ne: 'डाउनलोड' }} /><ArrowRight size={17} /></a> : <span className="muted"><L value={{ en: 'File unavailable', ne: 'फाइल उपलब्ध छैन' }} /></span>}</article>)}</div> : <EmptyState kind={{ en: 'documents', ne: 'कागजात' }} search={Boolean(query)} />}</>;
}
export function NoticeList({ category, limit, filters = false }: { category?: string; limit?: number; filters?: boolean }) {
  const all = published(useContent().notices); const { lang } = useLanguage(); const [selected, setSelected] = useState('All'); const [query, setQuery] = useState('');
  const items = all.filter(item => (!category || item.category === category) && (selected === 'All' || item.category === selected) && `${item.title.en} ${item.title.ne} ${item.excerpt.en} ${item.excerpt.ne}`.toLowerCase().includes(query.toLowerCase())).slice(0, limit);
  return <>{filters && <div className="filter-bar"><div className="filter-tabs">{['All', ...Object.keys(noticeCategoryLabels)].map(item => <button type="button" key={item} aria-pressed={selected === item} className={selected === item ? 'active' : ''} onClick={() => setSelected(item)}>{item === 'All' ? (lang === 'ne' ? 'सबै' : 'All updates') : text(noticeCategoryLabels[item as Notice['category']], lang)}</button>)}</div><SearchField value={query} change={setQuery} label={{ en: 'Search updates', ne: 'सूचना खोज्नुहोस्' }} /></div>}{items.length ? <div className="notice-list">{items.map(item => <article className="notice-item" key={item.id}><div className="notice-date">{item.date || 'ANTWU'}</div><div><div className="notice-meta"><span><L value={noticeCategoryLabels[item.category]} /></span>{item.urgent && <strong><L value={{ en: 'Important', ne: 'महत्त्वपूर्ण' }} /></strong>}</div><h2><L value={item.title} /></h2><p><L value={item.excerpt} /></p>{item.body && <details><summary><L value={{ en: 'Read update', ne: 'पूरा पढ्नुहोस्' }} /></summary><BodyText value={item.body} /></details>}{item.file && <a href={item.file} download className="text-link"><L value={{ en: 'Download attachment', ne: 'संलग्न फाइल डाउनलोड' }} /><ArrowRight size={15} /></a>}</div><ArrowRight className="notice-arrow" size={20} aria-hidden="true" /></article>)}</div> : <EmptyState kind={{ en: 'updates', ne: 'सूचना' }} search={Boolean(query)} compact={Boolean(limit)} />}</>;
}
export function BlogList({ limit }: { limit?: number }) {
  const all = published(useContent().blogPosts); const { lang } = useLanguage(); const [query, setQuery] = useState('');
  const items = all.filter(item => `${item.title.en} ${item.title.ne} ${item.excerpt.en} ${item.excerpt.ne}`.toLowerCase().includes(query.toLowerCase())).slice(0, limit);
  return <>{!limit && all.length > 0 && <div className="filter-bar"><span className="result-note">{all.length} <L value={{ en: 'published stories', ne: 'प्रकाशित लेख' }} /></span><SearchField value={query} change={setQuery} label={{ en: 'Search stories', ne: 'लेख खोज्नुहोस्' }} /></div>}{items.length ? <div className="blog-grid">{items.map(item => <Link href={`/blog/${item.slug}`} className="blog-card" key={item.id}>{item.image && <div className="blog-image"><Image src={item.image} alt={text(item.title, lang)} width={800} height={550} sizes="(max-width: 650px) 100vw, (max-width: 1000px) 50vw, 33vw" /></div>}<div className="blog-meta"><L value={item.category} /><span>{item.date}</span></div><h2><L value={item.title} /></h2><p><L value={item.excerpt} /></p><span className="text-link"><L value={{ en: 'Read story', ne: 'लेख पढ्नुहोस्' }} /><ArrowRight size={17} /></span></Link>)}</div> : <EmptyState kind={{ en: 'stories', ne: 'लेख' }} search={Boolean(query)} />}</>;
}
export function ContactDetails() {
  const row = useContent().settings[0]; const { lang } = useLanguage();
  return <address className="contact-stack">{row?.address && <div className="contact-card"><MapPin size={23} /><div><h3><L value={{ en: 'Visit the office', ne: 'कार्यालय आउनुहोस्' }} /></h3><p>{text(row.address, lang)}</p><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(row.address.en)}`} target="_blank" rel="noreferrer" className="text-link"><L value={{ en: 'Open in maps', ne: 'नक्सामा हेर्नुहोस्' }} /><ArrowRight size={14} /></a></div></div>}{row?.phone && <div className="contact-card"><Phone size={23} /><div><h3><L value={{ en: 'Call us', ne: 'फोन गर्नुहोस्' }} /></h3><a href={`tel:${row.phone.replace(/[^+\d]/g, '')}`}>{row.phone}</a></div></div>}{row?.email && <div className="contact-card"><Mail size={23} /><div><h3><L value={{ en: 'Write to us', ne: 'इमेल गर्नुहोस्' }} /></h3><a href={`mailto:${row.email}`}>{row.email}</a></div></div>}</address>;
}
export function OfficeAside() { return <aside className="aside-card"><span className="eyebrow"><L value={{ en: 'Here to help', ne: 'सहयोगका लागि' }} /></span><h2><L value={{ en: 'Looking for more information?', ne: 'थप जानकारी चाहिएको छ?' }} /></h2><p><L value={{ en: 'Contact the union office for enquiries, records and membership support.', ne: 'सोधपुछ, अभिलेख र सदस्यता सहयोगका लागि संघ कार्यालयमा सम्पर्क गर्नुहोस्।' }} /></p><Link href="/contact" className="button primary"><L value={{ en: 'Contact us', ne: 'सम्पर्क गर्नुहोस्' }} /><ArrowRight size={16} /></Link></aside>; }
